### ISSUE TITLE
Unknow variables in train.py

### ISSUE THREAD

**Issue by ErisGe** [kobeshegu/FreGAN_NeurIPS2022#1]
There are two variables which are not defined in the train.py.
They appear on lines 338: 'real_image_vis' and 342: 'real_image_2', respectively.
Could you tell me what they are?
Thanks!

**Comment by kobeshegu** [comment]
Hi，
real_image_vis and real_images2[0] are used for saving visualization results of our wavelet transformation during the training process.
You can simply set real_image_vis = real_image, and real_image_2 = real_image, or you can comment line 335 to 383.

**Comment by ErisGe** [comment]
oh, thanks!
