### ISSUE TITLE
Pre-trained models ?

### ISSUE THREAD

**Issue by SerChirag** [kobeshegu/FreGAN_NeurIPS2022#2]
Hi,
I was wondering if you have pertained models for this paper. I am looking for pre-trained models for few-shot datasets at 256×256 resolution.

~ Chirag

**Comment by kobeshegu** [comment]
Hi, Chirag,
Thanks for the interest, you can download the datasets from [here](https://drive.google.com/file/d/1aAJCZbXNHyraJ6Mi13dSbe7pTyfPXha0/view?usp=sharing) and train our model to reproduce our results.
